baseurl = "https://blog.jackdbai.dev/"
canonifyUrls = true
languageCode = "en-us"
title = "Master of None"
disableKinds = ["taxonomy", "taxonomyTerm"]

[params]
	description = "Specialization is for insects."

[markup.goldmark.renderer]
unsafe= true
