baseURL = "https://blog.jackdbai.dev"
title = "Master of None"
theme = "etch"
languageCode = "en-US"
enableInlineShortcodes = true
pygmentsCodeFences = true
pygmentsUseClasses = true

[author]
    name = "Jack"

[params]
  description = "Ramblings, thoughts, etc."
  copyright = "Copyright Â© 2022 Jack"
  dark = "on"
  highlight = true

[menu]
    [[menu.main]]
     identifier = "RSS"
     name = "RSS"
     title = "RSS"
     url = "/index.xml"
     weight = 10
     # 
     # [[menu.main]]
     #   identifier = "Twitter"
     #   name = "Twitter"
     #   title = "Twitter"
     #   url = "https://twitter.com/jackdbai"
     #   weight = 20

[permalinks]
  posts = "/:title/"

[markup.goldmark.renderer]
  # Allows HTML in Markdown
  unsafe = true
